[package]
name = "qr-on-desktop"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
image = "0.25.9"
arboard = "3.6.1"
rqrr = "0.10.1"

[dev-dependencies]
qrcode = "0.14.1"
